language: php
dist: trusty
php:
  - 7.0
services:
  - redis-server
  - mongodb
before_script:
  - composer self-update || true
  - yes '' | pecl install -f mongodb-1.1
  - bash -c 'while ! exec 6<>/dev/tcp/localhost/27017; do echo "$(date) - still trying to connect to mongo"; sleep 1; done'
script: ./build.php
after_script: ./vendor/bin/coveralls -v
